"""MoonSpace 全局配置常量。"""

# 窗口与渲染
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 270
WINDOW_SCALE = 2
WINDOW_WIDTH = SCREEN_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = SCREEN_HEIGHT * WINDOW_SCALE
FPS = 60
WINDOW_TITLE = "MoonSpace（月之隙）"

# 地图与像素规格
TILE_SIZE = 16
MAP_WIDTH = 960
MAP_HEIGHT = 540
MAP_WIDTH_TILES = (MAP_WIDTH + TILE_SIZE - 1) // TILE_SIZE
MAP_HEIGHT_TILES = (MAP_HEIGHT + TILE_SIZE - 1) // TILE_SIZE

# 场景独立世界尺寸。月谷继续使用 MAP_*，避免旧存档和教程地图被拉伸。
COURTYARD_WIDTH = 960
COURTYARD_HEIGHT = 640
GUANGHAN_WIDTH = 960
GUANGHAN_HEIGHT = 720

COURTYARD_SOUTH_SPAWN = (480, 470)
COURTYARD_NORTH_SPAWN = (480, 220)
GUANGHAN_SOUTH_SPAWN = (480, 580)

# 大地图默认摆放
PLAYER_START_X = 472
PLAYER_START_Y = 464

# 玩家移动
PLAYER_WALK_SPEED = 80
PLAYER_RUN_SPEED = 140
PLAYER_SIZE = (16, 24)

# 动画帧率
IDLE_ANIMATION_FPS = 2
WALK_ANIMATION_FPS = 8
INTERACT_ANIMATION_FPS = 4

# 输入动作名
ACTION_MOVE_UP = "move_up"
ACTION_MOVE_DOWN = "move_down"
ACTION_MOVE_LEFT = "move_left"
ACTION_MOVE_RIGHT = "move_right"
ACTION_RUN = "run"
ACTION_INTERACT = "interact"
ACTION_OPEN_RULE_BOOK = "open_rule_book"
ACTION_RESTART = "restart"
ACTION_QUIT = "quit"

ALL_ACTIONS = (
    ACTION_MOVE_UP,
    ACTION_MOVE_DOWN,
    ACTION_MOVE_LEFT,
    ACTION_MOVE_RIGHT,
    ACTION_RUN,
    ACTION_INTERACT,
    ACTION_OPEN_RULE_BOOK,
    ACTION_RESTART,
    ACTION_QUIT,
)
